### ISSUE TITLE
Whitelisting crashes Pi-hole 5.2 DNS resolver

### ISSUE THREAD

**Issue by ghost** [badsgahhl/pihole-browser-extension#36] opened 2020-11-30 21:00 UTC
Hey,

I updated Pi-hole to version 5.2 (FTL 5.3.1 // Web Interface 5.2)
When I whitelist a website via the edge plugin, the Pi-Hole DNS resolver crashes.
I have to login via IP to Pi-Hole (pi.hole don't work) and restart the DNS resolver in the settings dialog.

**Comment by badsgahhl** [comment] 2020-11-30 21:21
This is something that often occurred on my PiHole Installation after major updates of PiHole. Only reinstalling PiHole worked for me then.

I tested the extension with a fresh Installation of the current PiHole version. Whitelisting works in general. 

Try adding a domain to the whitelist via the Admin Interface. I probably think that this will crash your PiHole as well. The extension basically uses the same API Endpoint to add domains to the list.
After pressing the button in the extension, its on the side of PiHole to work right.
However what domain did you try to whitelist?

**Comment by ctrlcmdshft** [comment] 2020-12-01 22:33
Same issue on Firefox and tested on Admin interface and it does not crash it only crashes with extension whitelist feature.

**Comment by badsgahhl** [comment] 2020-12-01 23:00
So i tried a clean Docker Installation of PiHole aswell as a clean installation on debian. With both installations and different urls etc it worked to whitelist them via the extension. Without any crashes.

Which color did the extension show after you whitelisted a domain?

**Comment by ctrlcmdshft** [comment] 2020-12-02 00:08
extension goes red like pihole is disabled and then going to admin panel says cannot connect to api and i need to then reboot raspberry pi

**Comment by badsgahhl** [comment] 2020-12-02 06:51
I meant the color of the badge behind the url in the extension popup. After you click the whitelist button this should get some color.

**Comment by ctrlcmdshft** [comment] 2020-12-02 21:17
i click green button to whitelist current site then area where it says the current URL turns green then extension show pihole as offline/Err and then seconds later pihole display i use shows "unable to communicate with pihole. aborting" then i need to remove power and boot it back up

**Comment by badsgahhl** [comment] 2020-12-03 13:19
From my point of view this is a problem caused by the update of PiHole. PiHole reports to the extension that the whitelist has worked. If it crashes after that the extension has no control over it.

For me it works with a current clean installation of PiHole (and any browser with the extension). So I would recommend to reinstall PiHole.

**Comment by badsgahhl** [comment] 2021-01-04 20:44
I will close this here, as this is probably a error that is caused by updating PiHole.

**Closed by badsgahhl** 2021-01-04 20:44 UTC
Labels: bug
