### ISSUE TITLE
No Connection

### ISSUE THREAD

**Issue by n3roGit** [badsgahhl/pihole-browser-extension#62] opened 2022-01-10 16:57 UTC
Used version: Pi-hole v5.8.1 FTL v5.13 Web Interface v5.10.1

Problem:
![image](https://user-images.githubusercontent.com/8565847/148806216-997fdfcb-e6b1-43b8-b2f7-ac8e9f8b76cc.png)

Since the update to the latest version, the switch is always grayed out. However, in the settings it says "connected".
![image](https://user-images.githubusercontent.com/8565847/148806299-e9bee90c-4027-4f2b-84f0-6e506784ab42.png)

**Comment by badsgahhl** [comment] 2022-01-10 16:59
Duplicate of #54

**Closed by badsgahhl** 2022-01-10 16:59 UTC
Labels: bug
